SELECT emp1.LAST_NAME, 
    emp1.DEPARTMENT_ID,
    emp2.LAST_NAME AS "COLLEAGUE"
FROM EMPLOYEES emp1
JOIN EMPLOYEES emp2 on emp1.DEPARTMENT_ID = emp2.DEPARTMENT_ID
WHERE emp2.LAST_NAME != emp1.LAST_NAME AND 
    emp1.LAST_NAME= 'Davies'
;