SELECT emp1.LAST_NAME, 
    emp1.HIRE_DATE,
    emp2.LAST_NAME,
    emp2.HIRE_DATE
FROM EMPLOYEES emp1
JOIN EMPLOYEES emp2 on emp1.MANAGER_ID = emp2.EMPLOYEE_ID
WHERE emp1.HIRE_DATE < emp2.HIRE_DATE
;