SELECT LAST_NAME,
        EMPLOYEE_ID AS "EMP#", 
        (SELECT LAST_NAME FROM EMPLOYEES manager WHERE manager.EMPLOYEE_ID = e.MANAGER_ID ) AS MANAGER, 
         MANAGER_ID AS "MGR#" 
FROM EMPLOYEES e 
ORDER BY  EMPLOYEE_ID;