INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('BELGIQUE', 32, 0.21);
INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('FRANCE', 33, 0.2);
INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('AUTRICHE', 43, 0.2);

INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('ADMINISTRATEUR', 1);
INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('VENDEUR', 2);
INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('ACHETEUR', 3);

INSERT INTO PLATFORM(PLA_LABEL) VALUES ('STEAM');
INSERT INTO PLATFORM(PLA_LABEL) VALUES ('ORIGIN');
INSERT INTO PLATFORM(PLA_LABEL) VALUES ('PLAY STORE');

INSERT INTO UTILISATEUR(USR_LAST_NAME, USR_FIRST_NAME, USR_BIRTH_DATE, USR_ADDRESS, USR_CITY, USR_POSTAL_CODE, USR_PHONE, USR_MAIL, FK_ID_COUNTRY, FK_ID_RIGHT_ACCESS, USR_PASSWORD) VALUES ('VIC','BENJAMIN','07/03/1995','16 rue Rollin', 'Paris', '75005','0700000000', 'vic@et.esiea.fr','3','3','admin');
INSERT INTO UTILISATEUR(USR_LAST_NAME, USR_FIRST_NAME, USR_BIRTH_DATE, USR_ADDRESS, USR_CITY, USR_POSTAL_CODE, USR_PHONE, USR_MAIL, FK_ID_COUNTRY, FK_ID_RIGHT_ACCESS, USR_PASSWORD) VALUES ('GABEN','GABEN','08/05/1945','1 Volvo Street', 'Vulvo', '00000','Nope.img', 'gaben@valve.com','3','2','demo');
INSERT INTO UTILISATEUR(USR_LAST_NAME, USR_FIRST_NAME, USR_BIRTH_DATE, USR_ADDRESS, USR_CITY, USR_POSTAL_CODE, USR_PHONE, USR_MAIL, FK_ID_COUNTRY, FK_ID_RIGHT_ACCESS, USR_PASSWORD) VALUES ('FUEGO','EN LA CABANA','05/09/1949','84 chaussée d Alzemberg', 'Liege', '12005','0600000000', 'communication@et.esiea.fr','4','1','demo');

INSERT INTO GAME(GAM_LABEL, GAM_DESCRIPTION, FK_ID_PLATFORM) VALUES ('Battlefield 1','FPS reprenant le contexte de la première Guerre Mondiale',2);
INSERT INTO GAME(GAM_LABEL, GAM_DESCRIPTION, FK_ID_PLATFORM) VALUES ('Dota2','Apprentissage de la langue russe pour  les joueurs en Ouest-Europe',1);
INSERT INTO GAME(GAM_LABEL, GAM_DESCRIPTION, FK_ID_PLATFORM) VALUES ('Nier Automata','Le plus beau BeatThemAll de 2017',1);
INSERT INTO GAME(GAM_LABEL, GAM_DESCRIPTION, FK_ID_PLATFORM) VALUES ('TERRA_BATTLE','Un jeu de stratégie basé sur  le déplacement de tuiles de os personnages, le tout au bout  de vos doight',3);


INSERT INTO AUCTION (AUC_QUANTITY,AUC_PRICE,FK_ID_GAME,FK_ID_SELLER,FK_ID_RIGHT_ACCESS) VALUES (2000, 50, 1, 1, 3);
INSERT INTO AUCTION (AUC_QUANTITY,AUC_PRICE,FK_ID_GAME,FK_ID_SELLER,FK_ID_RIGHT_ACCESS) VALUES (1000, 0, 3, 2, 2);
INSERT INTO AUCTION (AUC_QUANTITY,AUC_PRICE,FK_ID_GAME,FK_ID_SELLER,FK_ID_RIGHT_ACCESS) VALUES (125, 35, 2, 2, 2);
INSERT INTO AUCTION (AUC_QUANTITY,AUC_PRICE,FK_ID_GAME,FK_ID_SELLER,FK_ID_RIGHT_ACCESS) VALUES (50, 2, 4, 2, 3);


INSERT INTO PROMOTION