INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('BELGIQUE', 32, 0.21);
INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('FRANCE', 33, 0.2);
INSERT INTO COUNTRY(COU_LABEL, COU_PHONE_EXTENSION, COU_TAX_RATE) VALUES ('AUTRICHE', 43, 0.2);

INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('ADMINISTRATEUR', 1);
INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('VENDEUR', 2);
INSERT INTO RIGHT_ACCESS(USI_LABEL,USI_LEVEL) VALUES ('ACHETEUR', 3);

INSERT INTO PLATFORM(PLA_LABEL) VALUES ('STEAM');
INSERT INTO PLATFORM(PLA_LABEL) VALUES ('ORIGIN');
INSERT INTO PLATFORM(PLA_LABEL) VALUES ('PLAY STORE');

